var coffeeTheme = {
  '--primary-color': '#795548',
  '--primary-on-secondary-color': '#795548',
  '--primary-hover-color': '#6d4c41',
  '--primary-selected-color': '#5d4037',
  '--primary-selected-hover-color': '#4e342e',
  '--primary-highlighted-color': '#3e2723',
  '--primary-text-color': '#d5d8df',
  '--text-color-on-primary': '#ffffff',
  '--text-color-on-inverted': '#323338',
  '--secondary-text-color': '#9699a6',
  '--placeholder-color': '#c3c6d4',
  '--icon-color': '#c3c6d4',
  '--link-color': '#a1887f',
  '--fixed-light-color': '#ffffff',
  '--fixed-dark-color': '#323338',
  '--primary-background-color': '#4e342e',
  '--primary-background-hover-color': 'rgba(103, 104, 121, 0.3)',
  '--secondary-background-color': '#3e2723',
  '--grey-background-color': '#3e2723',
  '--allgrey-background-color': '#3e2723',
  '--inverted-color-background': '#ffffff',
  '--disabled-text-color':
    'rgba(213, 216, 223, var(--disabled-component-opacity))',
  '--disabled-background-color': '#3c3f59',
  '--positive-color': '#4caf50',
  '--positive-color-hover': '#388e3c',
  '--positive-color-selected': '#2e7d32',
  '--positive-color-selected-hover': '#1b5e20',
  '--negative-color': '#d32f2f',
  '--negative-color-hover': '#c62828',
  '--negative-color-selected': '#b71c1c',
  '--negative-color-selected-hover': '#8b0000',
  '--private-color': '#d81b60',
  '--shareable-color': '#9c27b0',
  '--ui-border-color': '#797e93',
  '--ui-background-color': '#4b4e69',
  '--layout-border-color': '#4b4e69',
  '--warning-color': '#ff9800',
  '--warning-color-hover': '#fb8c00',
  '--warning-color-selected': '#f57c00',
  '--warning-color-selected-hover': '#ef6c00',
  '--brand-color': '#795548',
  '--brand-hover-color': '#6d4c41',
  '--brand-selected-color': '#5d4037',
  '--brand-selected-hover-color': '#4e342e',
  '--text-color-on-brand': '#ffffff',
  '--box-shadow-xs': '0px 4px 6px -4px rgba(9, 11, 25, 0.5)',
  '--box-shadow-small': '0px 4px 8px rgba(9, 11, 25, 0.5)',
  '--box-shadow-medium': '0px 6px 20px rgba(9, 11, 25, 0.5)',
  '--box-shadow-large': '0px 15px 50px rgba(9, 11, 25, 0.5)',
  '--primary-hover-on-secondary-color': '#6d4c41',
  '--primary-selected-color-rgb': '93, 64, 55',
  '--primary-selected-on-secondary-color': '#5d4037',
  '--primary-text-on-secondary-color': '#d5d8df',
  '--primary-background-color-rgb': '78, 52, 46',
  '--primary-background-hover-on-secondary-color': '#4b4e69',
  '--secondary-background-color-rgb': '62, 39, 35',
  '--secondary-text-on-secondary-color': '#9699a6',
  '--link-on-secondary-color': '#a1887f',
  '--modal-background-color': '#3e2723',
  '--dark-background-color': '#3e2723',
  '--dark-background-on-secondary-color': '#4b4e69',
  '--dialog-background-color': '#3e2723',
  '--label-background-color': '#4e342e',
  '--label-background-on-secondary-color': '#4e342e',
  '--icon-on-secondary-color': '#c3c6d4',
  '--placeholder-color-with-opacity': 'rgba(195, 198, 212, 0.1)',
  '--placeholder-on-secondary-color': '#c3c6d4',
  '--ui-border-on-secondary-color': '#797e93',
  '--layout-border-on-secondary-color': '#4b4e69',
  '--disabled-background-on-secondary-color': '#3c3f59',
  '--disabled-text-on-secondary-color':
    'rgba(\n    213,\n    216,\n    223,\n    var(--disabled-component-opacity)\n  )',
  '--box-shadow-mediun': '0px 6px 20px rgba(0, 0, 0, 0.2)',
  '--react-modal-background': 'rgba(62, 39, 35, 0.7)',
  '--application-background-color': '#3e2723',
  '--application-border-color': '#4b4e69',
  '--pulse-background-color': '#4e342e',
  '--pulse-background-color-rgb': '78, 52, 46',
  '--pulse-background-color-opacity': '#4e342e80',
  '--pulse-text-color': 'var(--text-color-on-inverted)',
  '--pulse-hover-background-color': '#5d4037',
  '--pulse-selected-background-color': '#6d4c41',
  '--pulse-highlight-background-color': '#6d4c41',
  '--surfce-color': '#3e2723',
  '--surface-border-color': '#4b4e69',
  '--card-background-color': 'var(--secondary-background-color)',
  '--card-hover-background-color': '#4b4e69',
  '--card-selected-background-color': '#5a5c74',
  '--card-selected-text-color': 'var(--text-color-on-inverted)',
  '--card-border-color': '#5a5c74',
  '--automations-hover-background-color': '#525672',
  '--automations-label-background-color': '#525672',
  '--automations-border-color': '#5a5c74',
  '--automations-account-usage-background-color': '#3e2723',
  '--automations-account-usage-dropdown-border-color': '#9699a6',
  '--automations-account-usage-progressbar-background-color': '#4b4e69',
  '--apps-svg-icon-invert': 'invert(1)',
  '--apps-code-color': '#fff',
  '--apps-feature-preview-color': '#3e2723',
  '--apps-tabs-border-color': '#393b52',
  '--text-color-on-card': 'var(--text-color-on-inverted)',
  '--avatar-border-color': 'var(--text-color-on-inverted)',
  '--modal-bottom-color': 'var(--surfce-color)',
  '--modal-free-indication-color': 'var(--primary-selected-color)',
  '--notification-unread-highlight-color': '#6d4c41',
  '--apps-marketplace-highlight-color': '#3e2723',
  '--redactor-context-background-color': '#3e2723',
  '--redactor-context-link-color': '#ffffff',
  '--ajax-spinner-gif-path':
    'url(https://cdn.monday.com/images/ajax_spinner_dark.gif)',
  '--scrollbar-color': 'var(--text-color-on-inverted)',
  '--monday-loader-gif-path':
    'url(https://cdn.monday.com/images/loader/dark_loader.gif)',
  '--hint-background-color': '#258750',
  '--transparent-overlay': 'rgba(62, 39, 35, 0.5) !important',
  '--avatar-background': 'rgba(73, 78, 103, 0.5)',
  '--ai-modal-background': 'var(--secondary-background-color)',
  '--ai-modal-border': 'var(--layout-border-color)',
  '--ai-modal-box-shadow': 'rgba(87, 174, 255, 0.16)',
};

window.coffeeTheme = coffeeTheme;
