var nightTheme = {
  '--primary-color': '#0073ea',
  '--primary-on-secondary-color': ['#0073ea', '#0073ea'],
  '--primary-hover-color': '#0060b9',
  '--primary-selected-color': '#133774',
  '--primary-selected-hover-color': '#0d2e65',
  '--primary-highlighted-color': '#0b2858',
  '--primary-text-color': '#eeeeee',
  '--text-color-on-primary': '#ffffff',
  '--text-color-on-inverted': '#111111',
  '--secondary-text-color': '#aaaaaa',
  '--placeholder-color': '#aaaaaa',
  '--icon-color': '#aaaaaa',
  '--link-color': '#69a7ef',
  '--fixed-light-color': '#ffffff',
  '--fixed-dark-color': '#111111',
  '--primary-background-color': '#111111',
  '--primary-background-hover-color': 'rgba(103, 104, 121, 0.3)',
  '--secondary-background-color': '#2c2c2c',
  '--grey-background-color': '#111111',
  '--allgrey-background-color': '#2c2c2c',
  '--inverted-color-background': '#eeeeee',
  '--disabled-text-color':
    'rgba(238, 238, 238, var(--disabled-component-opacity))',
  '--disabled-background-color': '#3a3a3a',
  '--positive-color': '#00854d',
  '--positive-color-hover': '#007038',
  '--positive-color-selected': '#025231',
  '--positive-color-selected-hover': '#194733',
  '--negative-color': '#d83a52',
  '--negative-color-hover': '#b63546',
  '--negative-color-selected': '#642830',
  '--negative-color-selected-hover': '#5a2027',
  '--private-color': '#f65f7c',
  '--shareable-color': '#9d50dd',
  '--ui-border-color': '#8d8d8d',
  '--ui-background-color': '#636363',
  '--layout-border-color': '#636363',
  '--warning-color': '#ffcb00',
  '--warning-color-hover': '#eaaa15',
  '--warning-color-selected': '#503e02',
  '--warning-color-selected-hover': '#402f00',
  '--brand-color': '#0073ea',
  '--brand-hover-color': '#0060b9',
  '--brand-selected-color': '#133774',
  '--brand-selected-hover-color': '#0d2e65',
  '--text-color-on-brand': '#ffffff',
  '--box-shadow-xs': '0px 4px 6px -4px #000000',
  '--box-shadow-small': '0px 4px 8px #000000',
  '--box-shadow-medium': '0px 6px 20px #000000',
  '--box-shadow-large': '0px 15px 50px #000000',
  '--color-grass_green-hover': '#116846',
  '--color-grass_green-selected': '#0a482e',
  '--color-done-green-hover': '#0f9b63',
  '--color-done-green-selected': '#096c43',
  '--color-done-green-selected-with-opacity': 'rgba(9, 108, 67, 0.6)',
  '--color-bright-green-hover': '#7ca32b',
  '--color-bright-green-selected': '#56721b',
  '--color-saladish-hover': '#9d8f3e',
  '--color-saladish-selected': '#6d6329',
  '--color-egg_yolk-hover': '#c29e11',
  '--color-egg_yolk-selected': '#886e09',
  '--color-egg_yolk-rgb': '255,213,51',
  '--color-working_orange-hover': '#c0873c',
  '--color-working_orange-selected': '#875e27',
  '--color-dark-orange-hover': '#c25531',
  '--color-dark-orange-selected': '#883a1f',
  '--color-peach-hover': '#c2888a',
  '--color-peach-selected': '#885f5f',
  '--color-sunset-hover': '#c26163',
  '--color-sunset-selected': '#884343',
  '--color-sunset-selected-with-opacity': 'rgba(136, 67, 67, 0.6)',
  '--color-stuck-red-hover': '#ad3f51',
  '--color-stuck-red-selected': '#792a36',
  '--color-dark-red-hover': '#92334c',
  '--color-dark-red-selected': '#662232',
  '--color-sofia_pink-hover': '#c21e71',
  '--color-sofia_pink-selected': '#88134d',
  '--color-lipstick-hover': '#c24e9a',
  '--color-lipstick-selected': '#88356a',
  '--color-bubble-hover': '#be80ba',
  '--color-bubble-selected': '#855981',
  '--color-purple-hover': '#8050ab',
  '--color-purple-selected': '#593776',
  '--color-dark_purple-hover': '#6344a3',
  '--color-dark_purple-selected': '#442e71',
  '--color-berry-hover': '#673971',
  '--color-berry-selected': '#47264d',
  '--color-dark_indigo': '#6129ff',
  '--color-dark_indigo-hover': '#4c18dc',
  '--color-dark_indigo-selected': '#3c13ae',
  '--color-indigo-hover': '#4b4ead',
  '--color-indigo-selected': '#333578',
  '--color-navy': '#5684c5',
  '--color-navy-hover': '#3468b2',
  '--color-navy-selected': '#24508f',
  '--color-bright-blue-hover': '#4c7cc1',
  '--color-bright-blue-selected': '#345686',
  '--color-dark-blue-hover': '#0f6d97',
  '--color-dark-blue-selected': '#094b69',
  '--color-aquamarine-hover': '#469e9b',
  '--color-aquamarine-selected': '#2f6e6b',
  '--color-chili-blue-hover': '#569ec3',
  '--color-chili-blue-selected': '#3b6e88',
  '--color-river-hover': '#588095',
  '--color-river-selected': '#3c5967',
  '--color-winter-hover': '#7b8895',
  '--color-winter-selected': '#555f67',
  '--color-explosive-hover': '#98999a',
  '--color-explosive-selected': '#6a6a6a',
  '--color-american_gray-hover': '#69696a',
  '--color-american_gray-selected': '#494949',
  '--color-blackish': '#7a7a7a',
  '--color-blackish-hover': '#525252',
  '--color-blackish-selected': '#383838',
  '--color-brown-hover': '#684943',
  '--color-brown-selected': '#48322c',
  '--color-orchid-hover': '#b4739a',
  '--color-orchid-selected': '#7e516c',
  '--color-tan-hover': '#978977',
  '--color-tan-selected': '#6a6053',
  '--color-sky-hover': '#90bac6',
  '--color-sky-selected': '#65828b',
  '--color-coffee-hover': '#a27b6f',
  '--color-coffee-selected': '#71564e',
  '--color-royal-hover': '#4474bb',
  '--color-royal-selected': '#305183',
  '--color-teal': '#4a8f98',
  '--color-teal-hover': '#347179',
  '--color-teal-selected': '#245960',
  '--color-lavender-hover': '#a294c8',
  '--color-lavender-selected': '#71688c',
  '--color-steel-hover': '#95a2be',
  '--color-steel-selected': '#687185',
  '--color-lilac-hover': '#8e8a9f',
  '--color-lilac-selected': '#63616f',
  '--color-pecan': '#806363',
  '--color-pecan-hover': '#674c4c',
  '--color-pecan-selected': '#513939',
  '--primary-hover-on-secondary-color': '#0060b9',
  '--primary-selected-color-rgb': '19,55,116',
  '--primary-selected-on-secondary-color': '#133774',
  '--primary-text-on-secondary-color': '#eeeeee',
  '--primary-background-color-rgb': '17,17,17',
  '--primary-background-hover-on-secondary-color': '#636363',
  '--secondary-background-color-rgb': '44,44,44',
  '--secondary-text-on-secondary-color': '#9699a6',
  '--link-on-secondary-color': '#69a7ef',
  '--modal-background-color': '#181b34',
  '--dark-background-color': '#2c2c2c',
  '--dark-background-on-secondary-color': '#4b4e69',
  '--dialog-background-color': '#2c2c2c',
  '--label-background-color': '#404b69',
  '--label-background-on-secondary-color': '#404b69',
  '--icon-on-secondary-color': '#aaaaaa',
  '--placeholder-color-with-opacity': 'rgba(170, 170, 170, 0.1)',
  '--placeholder-on-secondary-color': '#aaaaaa',
  '--ui-border-on-secondary-color': '#8d8d8d',
  '--layout-border-on-secondary-color': '#636363',
  '--disabled-background-on-secondary-color': '#3a3a3a',
  '--disabled-text-on-secondary-color':
    'rgba(238, 238, 238, var(--disabled-component-opacity))',
  '--box-shadow-mediun': '0px 6px 20px rgba(0, 0, 0, 0.2)',
  '--react-modal-background': 'rgba(53, 53, 55, 0.7)',
  '--application-background-color': '#111111',
  '--application-border-color': 'var(--layout-border-color)',
  '--pulse-background-color': '#272729',
  '--pulse-background-color-rgb': '39, 39, 41',
  '--pulse-background-color-opacity': '#27272980',
  '--pulse-text-color': 'var(--color-snow_white)',
  '--pulse-hover-background-color': '#393a40',
  '--pulse-selected-background-color': '#393a40',
  '--pulse-highlight-background-color': '#393a40',
  '--surfce-color': '#212121',
  '--surface-border-color': 'var(--layout-border-color)',
  '--transparent-overlay': 'rgba(34, 34, 34, 0.5) !important',
  '--card-background-color': 'var(--secondary-background-color)',
  '--card-hover-background-color': '#4c4d56',
  '--card-selected-background-color': 'var(--primary-selected-color)',
  '--card-selected-text-color': 'var(--primary-text-color)',
  '--card-border-color': '#5a5c74',
  '--automations-hover-background-color': '#525672',
  '--automations-label-background-color': '#525672',
  '--automations-border-color': '#5a5c74',
  '--automations-account-usage-background-color': '#1c1f3b',
  '--automations-account-usage-dropdown-border-color': '#9699a6',
  '--automations-account-usage-progressbar-background-color': '#4b4e69',
  '--apps-svg-icon-invert': 'invert(1)',
  '--apps-code-color': '#fff',
  '--apps-feature-preview-color': '#292f4c',
  '--apps-tabs-border-color': '#393b52',
  '--text-color-on-card': 'var(--color-snow_white)',
  '--avatar-border-color': 'var(--color-snow_white)',
  '--modal-bottom-color': 'var(--surfce-color)',
  '--modal-free-indication-color': 'var(--primary-selected-color)',
  '--notification-unread-highlight-color': '#59627b',
  '--apps-marketplace-highlight-color': '#292f4c',
  '--redactor-context-background-color': '#393b53',
  '--redactor-context-link-color': '#fff',
  '--ajax-spinner-gif-path':
    'url(https://cdn.monday.com/images/ajax_spinner_dark.gif)',
  '--scrollbar-color': 'var(--color-wolf_gray)',
  '--monday-loader-gif-path':
    'url(https://cdn.monday.com/images/loader/darth_loader.gif)',
  '--avatar-background': 'rgba(77, 77, 77, 0.5)',
  '--ai-modal-background': 'var(--secondary-background-color)',
  '--ai-modal-border': 'var(--layout-border-color)',
};

window.nightTheme = nightTheme;
